# Runs flutter test, format and analyze for error checking
# this workflow is run on every commit in the repository
# On pushes to master branch, builds and deploys to internal app sharing
# also creates a draft release that must be manually reviewed for release
# through release workflow

name: CI/CD
on: [ push, pull_request ]
jobs:
  ci:
    name: Run flutter ${{ matrix.category }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        category: [ format, analyze, test ]
      fail-fast: false
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2.3.4

      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1.1.4

      - name: Cache Flutter dependencies
        uses: actions/cache@v2.1.6
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ steps.get-flutter-version.version }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ steps.get-flutter-version.version }}

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Run formatting check with line length 120
        if: matrix.category == 'format'
        run: flutter format --dry-run . --set-exit-if-changed --line-length=120

      - name: Run Code Generation
        if: matrix.category != 'format'
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Run ${{ matrix.category }}
        if: matrix.category != 'format'
        run: flutter ${{ matrix.category }} --no-pub


  build:
    name: Build
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: ci
    outputs:
      release_notes: ${{ steps.extract-release-notes.outputs.changes }}
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2.3.4

      # Extract Release Notes from CHANGELOG.md
      - name: Extract release notes
        id: extract-release-notes
        uses: mindsers/changelog-reader-action@v2
        with:
          version: Unreleased

      - name: Setup Java
        uses: actions/setup-java@v2.1.0
        with:
          distribution: 'zulu'
          java-version: '12'

      - name: Get Flutter version
        id: get-flutter-version
        uses: zgosalvez/github-actions-get-flutter-version-env@v1.1.4

      - name: Cache Flutter dependencies
        uses: actions/cache@v2.1.6
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.OS }}-flutter-install-cache-${{ steps.get-flutter-version.version }}

      - name: Setup Flutter
        uses: subosito/flutter-action@v1.5.3
        with:
          flutter-version: ${{ steps.get-flutter-version.version }}

      - name: Install Flutter Dependencies
        run: flutter pub get

      - name: Provide Firebase Config
        id: firebase_config
        uses: timheuer/base64-to-file@v1.0.3
        with:
          fileName: google-services.json
          encodedString: ${{ secrets.FIREBASE_CONFIG_BASE64 }}
      - run: mv ${{ steps.firebase_config.outputs.filePath }} ./android/app/google-services.json

      - name: Run Code Generation
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build an Android App Bundle file
        run: flutter build appbundle

      - name: Upload the aab artifact
        uses: actions/upload-artifact@v2.2.4
        with:
          name: aab-artifact
          path: build/app/outputs/bundle/release/app-release.aab
          retention-days: 1
          if-no-files-found: error

  internal_app_share:
    name: Internal App Sharing
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: [ ci,build ]
    steps:
      - name: Generate What's New file
        run: echo ${{ needs.build.outputs.release_notes }} > whatsnew-en-US

      - name: Download aab-artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: aab-artifact

      - name: Publish to Google PlayStore
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
          packageName: dev.project_umbrella.umbrella_client
          releaseFiles: app-release.aab
          track: internalsharing
          whatsNewDirectory: ./

  # Create Release Draft only on pushes to master branch
  create_release_draft:
    name: Create Draft Release
    if: github.event_name != 'pull_request' && github.ref == 'refs/heads/master'
    needs: [ ci,build,internal_app_share ]
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repository
        uses: actions/checkout@v2.3.4

      # Remove old release drafts by using the curl request for the releases with draft flag
      - name: Remove Old Release Drafts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases \
            | tr '\r\n' ' ' \
            | jq '.[] | select(.draft == true) | .id' \
            | xargs -I '{}' \
          curl -X DELETE -H "Authorization: Bearer $GITHUB_TOKEN" https://api.github.com/repos/$GITHUB_REPOSITORY/releases/{}

      # Extract version name and number from pubspec.yaml
      - name: Extract App Version
        id: app_versions
        uses: its404/get-flutter-version@v1.0.0

      # Create new release draft - which is not publicly visible and requires manual acceptance
      - name: Create Release Draft
        id: createDraft
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.app_versions.outputs.version_number }}+${{ steps.app_versions.outputs.build_number }}
          body: ${{ needs.build.outputs.release_notes }}
          commit: ${{ github.ref }}
          draft: true
          prerelease: true